### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ocramz** [qnib/docker-consul#2]
- Please complete the section on cluster management actions
- In the Dockerfile you install `consul-webui` but the readme says otherwise

**Comment by ChristianKniep** [comment]
Will do once I find some time, on my way to a conference.
Please ping me again if it's not done next week.
I'll try...

Thx for pushing me to document proper. :)

**Comment by ocramz** [comment]
Hi @ChristianKniep , I'm working again on this; coordinating a Consul cluster with docker-compose . Documentation is lacking and since you're one of the few who seems to make this work It'd be really useful if you could update this documentation :) thanks!

**Comment by ChristianKniep** [comment]
I redid the README to show how it can be used in general.
If you want me to get into some detail, please feel free to reopen the issue. :)

**Comment by ocramz** [comment]
Thanks a lot ! 👍

**Comment by ChristianKniep** [comment]
As said, if you want to have something elaborated on, reopen...
